---
:ems:
  :ems_vmware:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
        :addition:
          :critical:
        :power:
          :critical:
:ems_refresh:
  :vmware_cloud:
    :get_public_images: false
:http_proxy:
  :vmware_cloud:
    :host:
    :password:
    :port:
    :user:
  :vmwarews:
    :host:
    :password:
    :port:
    :user:
:log:
  :level_vcloud: info
  :level_vim: warn
:workers:
  :ems_metrics_collector_worker_vmware:
    :inherits_from: ems_metrics_collector_worker
  :ems_operations_worker_vmware:
    :inherits_from: ems_operations_worker
    :memory_threshold: 1.gigabytes
  :ems_refresh_worker_vmware:
    :inherits_from: ems_refresh_worker
  :ems_refresh_worker_vmware_cloud:
    :inherits_from: ems_refresh_worker
  :ems_refresh_worker_vmware_cloud_network:
    :inherits_from: ems_refresh_worker
  :event_catcher_vmware:
    :ems_event_max_wait: 60
    :flooding_monitor_enabled: true
    :inherits_from: event_catcher
    :poll: 1.seconds
  :event_catcher_vmware_cloud:
    :amqp_heartbeat: 30
    :amqp_port: 5672
    :amqp_recovery_attempts: 4
    :capacity: 50
    :duration: 10.seconds
    :inherits_from: event_catcher
    :poll: 15.seconds
